"""Catalog section: the analysis/output leads — stages fill (6.5), t3 (6.6),
project (6.7), roundtrip (6.8), harness meta (6.9).  Order is part of the
catalog contract; this list is spliced verbatim into catalog.py's _SEMANTIC
(frozen, never shrinks).
"""

# (probeId, kind, payloadType, description)
ANALYSIS_LEADS = [
    # ---- 6.5 stage fill (S4 fill-verdict) ----
    ("graph-model.fill.assign", "value", "{nodeId,status,source,why}",
     "the honest fill verdict per node AND its reason"),
    ("graph-model.fill.origin", "value", "{nodeId,origin}",
     "the origin classification (assumed debt vs given external)"),
    ("graph-model.fill.greenGuard", "decision", "{nodeId,requestedGreen,allowedGreen,reason}",
     "the guard that structurally forbids faked green; branch-not-taken: what WOULD allow green (a real compiler verdict)"),
    ("graph-model.fill.outline", "value", "{nodeId,outline,note}",
     "outline is deliberately null this round"),
    ("graph-model.fill.summary", "state", "{counts}",
     "the honest-ceiling tally — green MUST be 0"),
    # ---- 6.6 stage t3 (S5) ----
    ("graph-model.t3.universe", "value", "{declNodeIds,excluded,reason}",
     "which nodes are in the reachability universe (and why the module is excluded)"),
    ("graph-model.t3.roots", "value", "{rootIds,source}",
     "the roots fed to reachability — declared, not inferred"),
    ("graph-model.t3.rustworkx.build.nodesIn", "call", "{indexById,nodeCount}",
     "the nodes added to the rustworkx PyDiGraph (construction input)"),
    ("graph-model.t3.rustworkx.build.edgesIn", "call", "{edges,edgeCount,usedOnlyResolved}",
     "the edges added — ONLY resolved edges; confirms unresolved leads were excluded"),
    ("graph-model.t3.rustworkx.descendants", "value", "{perRoot}",
     "rustworkx.descendants(root) per root — the raw reachability output"),
    ("graph-model.t3.rustworkx.reachable", "output", "{reachableSet}",
     "union of roots + descendants: the reachable set OUT"),
    ("graph-model.t3.rustworkx.unused", "output", "{unusedSet}",
     "universe − reachable; the unreferenced decl should appear here"),
    ("graph-model.t3.networkx.build", "call", "{nodeCount,edgeCount}",
     "the parallel NetworkX DiGraph construction (mandatory cross-check)"),
    ("graph-model.t3.networkx.reachable", "value", "{reachableSet}",
     "the NetworkX descendants-based reachable set"),
    ("graph-model.t3.networkx.unused", "value", "{unusedSet}",
     "the NetworkX unused set"),
    ("graph-model.t3.crosscheck.reachable", "decision", "{rustworkx,networkx,agree,symmetricDiff}",
     "the two libraries must agree EXACTLY; any symmetric diff = a library-integration bug, fail"),
    ("graph-model.t3.scc.rustworkx", "value", "{sccs}",
     "Tarjan SCC via rustworkx (fixture is acyclic → all singletons)"),
    ("graph-model.t3.scc.networkx", "value", "{sccs}",
     "Tarjan SCC via NetworkX (must match rustworkx)"),
    ("graph-model.t3.condensation.isDAG", "decision", "{condensationEdges,isDAG}",
     "condensation-of-SCCs must be a DAG; not-a-DAG = a bug in SCC/condensation"),
    ("graph-model.t3.cap", "value", "{johnsonLengthBound,nodeCap,note}",
     "any bound logged — no silent caps (Contract 3.5 / rule 8)"),
    ("graph-model.t3.result", "state", "T3Result",
     "the full T3Result with the honest soundness caveat carried inline"),
    # ---- 6.7 stage project (S6) ----
    ("graph-model.project.text.tileOrder", "value", "{orderedSpans}",
     "the span tiling order used to reprint the source"),
    ("graph-model.project.text.emit", "output", "{bytes,byteLen,sha256}",
     "the text projection output (the reprinted source)"),
    ("graph-model.project.text.idsCarried", "value", "{spanToNodeId}",
     "which node id each emitted span carries — text carries ids via spans"),
    ("graph-model.project.graphjson.nodes", "value", "{nodes,count}",
     "the graph-JSON node array"),
    ("graph-model.project.graphjson.edges", "value", "{edges,count,resolvedOnly,leadsCarriedSeparately}",
     "the graph-JSON edge array — unresolved leads carried in a separate leads field, never mixed into edges"),
    ("graph-model.project.graphjson.emit", "output", "{json,sha256,conformsToSchema}",
     "the {nodes,edges} JSON output + schema-conformance flag"),
    ("graph-model.project.flat.emit", "output", "{rows,count}",
     "the flat node-list projection (T3-derived reachable/unused clearly labeled, never mixed into fill)"),
    ("graph-model.project.ids.text", "value", "{ids}",
     "node id set recovered from the text projection (via re-ingest)"),
    ("graph-model.project.ids.graphjson", "value", "{ids}",
     "node id set present in graph-JSON"),
    ("graph-model.project.ids.flat", "value", "{ids}",
     "node id set present in the flat list"),
    ("graph-model.project.ids.agree", "decision", "{textIds,graphIds,flatIds,allEqual,diffs}",
     "do the three projections carry identical ids? any diff = a projection dropped or renamed a node"),
    # ---- 6.8 stage roundtrip (S7) ----
    ("graph-model.roundtrip.reprint", "value", "{reprintBytes,byteLen,sha256}",
     "the text→model→text reprinted bytes"),
    ("graph-model.roundtrip.compare.len", "decision", "{sourceLen,reprintLen,equal}",
     "the cheap first check: lengths match?"),
    ("graph-model.roundtrip.compare.hash", "decision", "{sourceSha256,reprintSha256,equal}",
     "do content hashes match?"),
    ("graph-model.roundtrip.firstDivergence", "value", "{index,sourceByte,reprintByte,contextBefore,contextAfter}",
     "the FIRST byte where source and reprint diverge (null if identical) — the precise diff locator"),
    ("graph-model.roundtrip.diff", "value", "{byteDiff,count}",
     "the full byte diff list (no silent truncation)"),
    ("graph-model.roundtrip.reingest.idsMatch", "decision", "{originalIds,reingestedIds,equal}",
     "re-ingesting the reprint yields the SAME content-addressed ids — ids are stable across the round trip"),
    ("graph-model.roundtrip.fixpoint2", "value", "{modelStable,note}",
     "the stronger fixpoint (idempotence): a second round trip changes nothing"),
    ("graph-model.roundtrip.verdict", "decision", "{pass,failureClass}",
     "pass/fail with the NAMED failure class (name the failure class before the fix)"),
    # ---- 6.9 stage harness (meta) ----
    ("graph-model.harness.run.begin", "state", "{runId,inputSha256,startClock}",
     "the run boundary opens; deterministic clock resets to 0"),
    ("graph-model.harness.importGate", "decision", "{declaredDeps,observedImports,violations,pass}",
     "the import-boundary gate (rule 3): did the cell reach outside its declared deps?"),
    ("graph-model.harness.clock", "state", "{logicalClock}",
     "the monotonic per-cell counter driving deterministic causal ordering"),
    ("graph-model.harness.error", "error", "{stage,errorClass,message,causeId}",
     "any caught error/exception on the bus (every caught error gets a tap)"),
    ("graph-model.harness.run.end", "state", "{runId,endClock,eventCount,ok}",
     "the run boundary closes; total event count is a no-silent-loss check"),
]
