"""Catalog section: the build-pipeline leads — stages schema (6.1), ingest
(6.2), node (6.3), edge (6.4).  Order is part of the catalog contract; this
list is spliced verbatim into catalog.py's _SEMANTIC (frozen, never shrinks).
"""

# (probeId, kind, payloadType, description)
PIPELINE_LEADS = [
    # ---- 6.1 stage schema (S0 schema-freeze) ----
    ("graph-model.schema.load.ts", "value", "{path,bytes,sha256}",
     "the graph-schema.ts type artifact the cell froze (byte-mirrored from the "
     "canonical projection packages/schema/gen/graph-schema.ts), and its hash"),
    ("graph-model.schema.load.json", "value", "{path,bytes,sha256}",
     "the schema.json machine spec (the canonical source of truth) and its hash"),
    ("graph-model.schema.load.md", "value", "{path,bytes,sha256}",
     "the schema.md human spec and its hash"),
    ("graph-model.schema.version", "value", "{schemaVersion}",
     "the frozen version tag every downstream consumer pins to"),
    ("graph-model.schema.hash", "value", "{schemaHash}",
     "the identity of the constitution; a bump here breaks pinned consumers"),
    ("graph-model.schema.nodeKinds", "value", "string[]",
     "the node kinds parsed out of the schema (cross-artifact check input)"),
    ("graph-model.schema.edgeKinds", "value", "string[]",
     "the edge kinds parsed out of the schema"),
    ("graph-model.schema.crosscheck", "decision", "{tsKinds,jsonKinds,mdKinds,agree,diff}",
     "whether all three artifacts describe the SAME kinds; the diff names which artifact drifted"),
    ("graph-model.schema.codegen", "value", "{from,to,generated}",
     "that schema.md was generated from JSON, not hand-forked (graph-schema.ts "
     "is byte-mirrored from canonical, gated separately by the S0 drift check)"),
    ("graph-model.schema.freeze.result", "state", "{frozen,version,hash,artifacts}",
     "the freeze committed — the moment the constitution becomes immutable for this build"),
    # ---- 6.2 stage ingest (S1) ----
    ("graph-model.ingest.source.read", "input", "{file,byteLen,sha256,encoding}",
     "the raw source buffer the round-trip must reproduce byte-for-byte"),
    ("graph-model.ingest.roots.declared", "value", "{roots,source}",
     "the entry roots were DECLARED, not inferred — no silent entrypoint assumption"),
    ("graph-model.ingest.decl.raw", "node", "{ordinal,kind,name,byteStart,byteEnd,rawText,role}",
     "one lead per hand-written declaration record ingested, pre-Node"),
    ("graph-model.ingest.ref.raw", "value", "{fromDecl,refName,kind,atByte}",
     "one lead per hand-written use-site, pre-edge"),
    ("graph-model.ingest.trivia.span", "value", "{byteStart,byteEnd,text}",
     "the inter-decl whitespace/newlines were captured (the usual round-trip killer)"),
    ("graph-model.ingest.coverage.precheck", "decision", "{spans,coversFullRange,gaps,overlaps}",
     "do decl+trivia spans tile [0,byteLen) exactly at ingest? a gap here predicts an S7 round-trip failure"),
    ("graph-model.ingest.count", "value", "{declCount,refCount,triviaCount}",
     "the tally of everything ingested (a no-silent-cap lead)"),
    # ---- 6.3 stage node (S2 node-build) ----
    ("graph-model.node.canonicalName", "value", "{raw,canonicalName}",
     "how a raw name became a qualified name"),
    ("graph-model.node.normalizedSpan", "value", "{file,path,rawSpan,normalizedSpan}",
     "WHY the id is stable across reformatting: the structural locator feeds the hash, raw bytes do NOT"),
    ("graph-model.node.id.inputs", "value", "{lang,kind,canonicalName,normalizedSpan,domainTag}",
     "the EXACT tuple fed to the hash (content-addressed ID hash: inputs)"),
    ("graph-model.node.id.preimage", "value", "{preimageString,encoding,delimiter}",
     "the serialized byte preimage before hashing — lets you reproduce the hash by hand"),
    ("graph-model.node.id.hash", "value", "{algo,fullHex,truncated,nodeId}",
     "the resulting id (content-addressed ID hash: result)"),
    ("graph-model.node.create", "node", "{node}",
     "the full Node object emitted, conformant to the Frozen Schema (tap every node creation)"),
    ("graph-model.node.provenance", "value", "{tier,extractor,resolved}",
     "the provenance stamp — no anonymous data in the graph"),
    ("graph-model.node.id.collision", "decision", "{nodeId,firstSeenOrdinal,dupOrdinal,collided}",
     "did two decls hash equal? a silent collision would merge two nodes into one"),
    ("graph-model.node.table", "state", "{byId,byName,count}",
     "the assembled symbol table that S3 resolves edges against"),
    # ---- 6.4 stage edge (S3 edge-build) ----
    ("graph-model.edge.resolve.attempt", "decision", "{refName,candidatesByName,chosenDstId,resolved,reason}",
     "the resolution decision AND the branch not taken (why unresolved, if so)"),
    ("graph-model.edge.resolve.resolved", "branch", "{srcId,dstId,resolver}",
     "the resolved=true path taken (a ref binds to a real node)"),
    ("graph-model.edge.resolve.unresolved", "branch", "{srcId,dstPlaceholder,resolver,reason}",
     "the resolved=false path: a LEAD, not an edge; may never be shown as a real relationship"),
    ("graph-model.edge.id.inputs", "value", "{kind,srcId,dstId,domainTag}",
     "the edge-id hash inputs"),
    ("graph-model.edge.id.hash", "value", "{algo,fullHex,edgeId}",
     "the resulting edge id"),
    ("graph-model.edge.create", "edge", "{edge}",
     "the full Edge object, carrying its resolved flag (tap every edge creation)"),
    ("graph-model.edge.provenance", "value", "{tier,extractor}",
     "the edge provenance stamp"),
    ("graph-model.edge.rejected", "edge", "{candidate,reason}",
     "any candidate edge NOT created and why (e.g. src is not a node)"),
    ("graph-model.edge.resolvedSet", "state", "{resolvedEdges,unresolvedLeads}",
     "the split that S5 depends on: ONLY resolvedEdges may enter the T3 graph"),
]
