"""Pin assertion helper: read the PIN file and fail fast on any schema drift.

Every consuming cell asserts the pin at startup:

    import pin
    schema_obj = pin.assert_pin()   # raises SchemaPinMismatch on drift

The PIN file is two lines (`schemaVersion v0` / `schemaHash <64 hex>`) and is
regenerated by `schemagen.py --write`; `gen/pin.ts` mirrors it for TypeScript.
"""
import json
from pathlib import Path

try:
    from .schema_tools import check_pin, schema_hash
except ImportError:  # imported flat (packages/schema on sys.path)
    from schema_tools import check_pin, schema_hash

PKG_ROOT = Path(__file__).resolve().parent
PIN_PATH = PKG_ROOT / "PIN"
SCHEMA_PATH = PKG_ROOT / "schema.json"


def read_pin(pin_path=PIN_PATH):
    """Parse PIN into (pinned_version, pinned_hash)."""
    fields = {}
    for line in Path(pin_path).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        key, value = line.split(None, 1)
        fields[key] = value.strip()
    return fields["schemaVersion"], fields["schemaHash"]


def assert_pin(schema_path=SCHEMA_PATH, pin_path=PIN_PATH):
    """Assert schema.json still matches the PIN; return the parsed schema."""
    pinned_version, pinned_hash = read_pin(pin_path)
    schema_obj = json.loads(Path(schema_path).read_text(encoding="utf-8"))
    check_pin(pinned_version, pinned_hash,
              schema_obj["schemaVersion"], schema_hash(schema_obj))
    return schema_obj
