"""Probe catalog section: LaTeX + Typst docks, S3 ASSEMBLE, S4 T3 graph
properties (spec §6.6–§6.9).

One section of the exhaustive §6 enumeration — aggregated, IN ORDER, by
catalog.py (the probeCatalog() source of truth).  Entry shape:
(probeId, kind, payloadType, description).
"""

from __future__ import annotations

CATALOG_DOCS_GRAPH: list[tuple[str, str, str, str]] = [
    # ---- §6.6 S2·LaTeX DOCK (DESIGN/STUB) ----------------------------------
    ("extractor.t2.latex.backend.select", "decision", "{chosen, reason}",
     "Decision D3: LaTeXML (public-domain, embed) vs texlab (GPL-3.0, subprocess only). Default LaTeXML."),
    ("extractor.t2.latex.latexml.run", "call", "{cmd, exit}",
     "DORMANT (design-stub): latexml main.tex --dest=out.xml — two-pass label/ref/cite resolution."),
    ("extractor.t2.latex.xml.parse", "value", "{xmlIdCount, idrefCount}",
     "DORMANT (design-stub): XPath over xml:id/idref — a genuine nodes+edges graph."),
    ("extractor.t2.latex.ref.candidate", "edge", "{refSpan, targetLabel}",
     "A \\ref/\\eqref/\\cref -> \\label candidate (stub round: from T1 label_reference anchors)."),
    ("extractor.t2.latex.ref.resolve.decision", "decision", "{candidate, outcome, boundDstId|null, reason}",
     "Resolved (idref->xml:id) vs unresolved (undefined ref). Stub round: always a lead."),
    ("extractor.t2.latex.cite.candidate", "edge", "{citeSpan, bibKey, resolved}",
     "\\cite -> bib entry candidate."),
    ("extractor.t2.latex.include.candidate", "edge", "{includeSpan, targetFile}",
     "\\input/\\include -> includes candidate (cross-file project graph)."),
    ("extractor.t2.latex.aux.oracle", "value", "{label, auxNumber, latexmlNumber, agree}",
     "DORMANT (design-stub): compiler-as-oracle — resolved refs vs the real LaTeX run's .aux numbers."),
    ("extractor.t2.latex.texlab.lsp", "call", "{method, params}",
     "DORMANT (design-stub): texlab JSON-RPC traffic — SUBPROCESS ONLY (GPL-3.0), never linked."),
    ("extractor.t2.latex.edge.rejected", "edge", "{candidate, reason}",
     "Rejected: auto-id not promoted, duplicate \\label, ref into non-ingested file."),
    ("extractor.t2.latex.unused.label", "value", "{label, definedAt, referenced}",
     "texlab/LaTeXML unused-label finding (T3-ish dangling check the backend gives for free)."),
    ("extractor.t2.latex.honest_ceiling", "state", "HonestCeiling",
     "LaTeX dock declaration: TeX-emulation grade when live; Turing-complete macros are best-effort."),

    # ---- §6.7 S2·Typst DOCK (DESIGN/STUB) ----------------------------------
    ("extractor.t2.typst.syntax.parse", "value", "{syntaxKinds}",
     "typst-syntax SyntaxKind anchors present (Ref carries target text; ModuleImport carries path) — none resolved."),
    ("extractor.t2.typst.ide.resolve", "call", "{op}",
     "DORMANT (design-stub): typst-ide definition/analyze_labels/analyze_import."),
    ("extractor.t2.typst.eval.run", "call", "{cmd, exit}",
     "DORMANT (design-stub): typst eval — introspect the COMPILED document's ref elements."),
    ("extractor.t2.typst.query.deprecated", "decision", "{reason}",
     "Decision D4: typst query subcommand DEPRECATED in Typst 0.15.0 (PR #7362) -> use typst eval."),
    ("extractor.t2.typst.ref.candidate", "edge", "{refSpan, targetLabel}",
     "@ref -> <label> candidate."),
    ("extractor.t2.typst.ref.resolve.decision", "decision", "{candidate, outcome, reason}",
     "Resolved (label exists) vs unresolved (dangling @ref = hard compile error). Stub round: always a lead."),
    ("extractor.t2.typst.import.edge", "edge", "{srcModule, dstModule}",
     "ModuleImport -> imports candidate."),
    ("extractor.t2.typst.pinmain.warning", "state", "{reason}",
     "Cross-file label resolution needs a pinned main entry (tinymist.pinMain)."),
    ("extractor.t2.typst.edge.rejected", "edge", "{candidate, reason}",
     "Rejected: ref into non-ingested module, duplicate @ref."),
    ("extractor.t2.typst.danglingref.error", "error", "{refSpan, targetLabel, compilerError}",
     "DORMANT (design-stub): a dangling @ref surfaced as a Typst compile error — free dangling-edge detection."),
    ("extractor.t2.typst.honest_ceiling", "state", "HonestCeiling",
     "Typst dock declaration: name-resolution grade when live; no unused-label detection; never typst-lsp."),

    # ---- §6.8 S3 ASSEMBLE ---------------------------------------------------
    ("extractor.assemble.edge.normalize", "edge", "{candidate, schemaEdge}",
     "Candidate -> Frozen-Schema Edge{id,kind,srcId,dstId,resolved,resolver,provenance}."),
    ("extractor.assemble.edge.id", "value", "{edgeId, preimage}",
     "The edge's content-addressed id and exact preimage (deterministic dedup)."),
    ("extractor.assemble.edge.unresolved.placeholder", "node", "{placeholderId, dstName, reason}",
     "resolved=false -> dstId is an explicit 'unresolved:' placeholder; never a fabricated real node."),
    ("extractor.assemble.edge.dedup", "decision", "{keptEdgeId, droppedDuplicateOf}",
     "Duplicate (kind,src,dst) collapsed."),
    ("extractor.assemble.provenance.audit", "value", "{totalNodes, totalEdges, withProvenance}",
     "Asserts every node and edge carries provenance — no anonymous data in the graph."),
    ("extractor.assemble.resolved.tally", "value", "{perDock}",
     "resolved/unresolved/rejected count per dock — the fastest read of the whole cell's honest ceiling."),
    ("extractor.assemble.graph.emit", "output", "{nodeCount, edgeCount, resolvedEdges, unresolvedLeads}",
     "The {nodes,edges} artifact leaving S3, conforming to the Frozen Schema."),
    ("extractor.assemble.green.audit", "decision", "{nodeId, lang, origin, source, attested, tierAllows}",
     "LEAN-DOCK round: every green fill audited at assemble — origin 'checked' + registered checker attestation + CT tier, or unbacked-green."),
    ("extractor.green.enforcement.violation", "error", "{nodeId, origin, source, tier}",
     "A green fill without a kernel attestation (failure class unbacked-green). Must never fire; asserted by the forged-green guard test."),

    # ---- §6.9 S4 T3 GRAPH PROPERTIES ---------------------------------------
    ("extractor.t3.graph.input", "input", "{nodeCount, resolvedEdgeCount}",
     "The graph fed to rustworkx."),
    ("extractor.t3.graph.exclude.unresolved", "decision", "{excludedCount, reason}",
     "Decision D6 — THE honesty gate of T3: resolved=false is a lead, not an edge; leads are excluded."),
    ("extractor.t3.rustworkx.build", "call", "{lib, nodes, edges}",
     "Build the PyDiGraph."),
    ("extractor.t3.scc.tarjan", "value", "{sccs, multiNodeSccCount}",
     "Tarjan SCC; any SCC with >1 node is a mutual cycle."),
    ("extractor.t3.cycle.johnson", "value", "{cycles, lengthBound}",
     "Johnson enumeration of elementary cycles (length-bounded)."),
    ("extractor.t3.cycle.bound.cap", "decision", "{lengthBound, truncated}",
     "Johnson can be exponential; the bound is a cap -> logged, never silent."),
    ("extractor.t3.reach.descendants", "value", "{roots, reachableSet}",
     "Reachability from declared roots — records the EXACT roots used."),
    ("extractor.t3.unused.complement", "value", "{unusedSet}",
     "Complement-of-reachable-from-roots -> the dead/unused set (unreachable-from-roots sense)."),
    ("extractor.t3.condensation.dag", "value", "{condensationIsDag}",
     "Invariant: the condensation of SCCs MUST be a DAG; false = SCC computation bug."),
    ("extractor.t3.networkx.crosscheck", "call", "{lib}",
     "Recompute SCC/cycles/reachable-set with NetworkX."),
    ("extractor.t3.agreement.diff", "decision", "{agree, diff}",
     "rustworkx and NetworkX must agree exactly; any diff is a bug in one library's use."),
    ("extractor.t3.soundness.blindspots", "state", "{caveat, missingEdgeClasses}",
     "Logged next to EVERY unused claim: reachability-'unused' is only as complete as the edge set."),
    ("extractor.t3.unreferenced", "value", "{unreferencedSet}",
     "The UNREFERENCED set (nothing points at it) — distinct from unusedSet; never conflated (§5.10)."),
    ("extractor.t3.roots.selected", "decision", "{roots, reason}",
     "The reachability root set chosen; a wrong root set silently inflates unused — so this is explicit."),
    ("extractor.t3.export", "output", "{format, nodes, edges, path}",
     "The T3 graph serialized (DOT/JSON) — the artifact a later gap-analysis round loads."),
    ("extractor.t3.import.cycle.na", "branch", "{lang, reason}",
     "Cycle detection skipped for Go/Lean import graphs (compile-time DAG); Python imports DO run Tarjan."),
]
