/** Catalog sections S2 conn + S3 lsp (entries from §6; refreshed in the
 *  adversarial claim audit to match the emitted payloads: capabilities.server's
 *  field list, and error.protocol's kind union — the declared 'versionMismatch'
 *  kind was never emitted by any code path (version staleness fires
 *  editor.diag.version.guard instead), so it was removed). */

import { p, type ProbeSpec } from "./spec.js";

export const CONN_PROBES: ProbeSpec[] = [
  // ── S2 conn ─────────────────────────────────────────────────────────────────
  p("editor.conn.capability.input", "conn", "input",
    "{lang,tier:'CT'|'S'|'G'|'P',handleKind,handleRef}",
    "The capability(lang) value from Tree 2; the tier decides whether green is even allowed downstream."),
  p("editor.conn.transport.open", "conn", "call",
    "{kind:'websocket'|'worker'|'inmemory',url?,secretPresent,secretLast4?}",
    "Opening the transport; tokens redacted to presence + last-4."),
  p("editor.conn.transport.state", "conn", "state",
    "{phase:'connecting'|'open'|'closed'|'error',detail}",
    "Transport lifecycle; a stuck 'connecting' explains 'no diagnostics ever'."),
  p("editor.conn.client.init", "conn", "call", "{clientName,initializeParams}",
    "The initialize request params the language client sent."),
  p("editor.conn.positionEncoding.negotiate", "conn", "decision",
    "{requested:'utf-8',accepted,winner,reason}",
    "The negotiated position encoding; governs whether byte spans and editor columns agree."),
  p("editor.conn.capabilities.server", "conn", "value",
    "{hoverProvider,definitionProvider,documentSymbolProvider,callHierarchyProvider,typeHierarchyProvider,semanticTokensProvider,completionProvider,foldingRangeProvider}",
    "What the server says it can do; callHierarchy/typeHierarchy are OPTIONAL — never assumed."),
  p("editor.conn.serverInfo", "conn", "value", "{name,version}",
    "The server's self-reported identity; pins which server produced a given verdict."),
  p("editor.conn.capability.missing", "conn", "branch",
    "{missing:[string],degradeTo,reason}",
    "An optional capability was absent and we degraded — the server, not the editor, lacks it."),
  p("editor.conn.tier.guard", "conn", "decision", "{tier,liveGreenAllowed,reason}",
    "If tier != CT, live green from this server is forbidden; upstream half of the honesty guard."),
  p("editor.conn.handshake.fail", "conn", "error", "{phase,message}", "initialize failed."),
  p("editor.conn.reconnect", "conn", "state", "{attempt,maxAttempts,backoffMs}",
    "Retry accounting; the retry bound is a cap and is logged here, never silent."),
  p("editor.conn.dispose", "conn", "state", "{clientName}", "Client shut down."),
];

export const LSP_PROBES: ProbeSpec[] = [
  // ── S3 lsp ──────────────────────────────────────────────────────────────────
  p("editor.lsp.out.didOpen", "lsp", "call", "{uri,languageId,version,textLength}",
    "The didOpen we sent; if wrong, the server sees the wrong document."),
  p("editor.lsp.out.didChange", "lsp", "call", "{version,contentChanges,incremental}",
    "Every didChange; its version must match the model version that produced it.", true),
  p("editor.lsp.out.request", "lsp", "call", "{id,method,params}",
    "Every outbound request (hover, definition, documentSymbol, …).", true),
  p("editor.lsp.in.response", "lsp", "call", "{id,method,result?,error?,clockDelta}",
    "Every inbound response, correlated to its request id.", true),
  p("editor.lsp.in.notification", "lsp", "call", "{method,params}",
    "Every inbound notification other than diagnostics.", true),
  p("editor.lsp.in.diagnostics", "lsp", "call",
    "{uri,version,count,diagnostics:[{range,severity,message,source,code}]}",
    "The raw publishDiagnostics payload; the single most important inbound message for this cell."),
  p("editor.lsp.raw.frame", "lsp", "call", "{direction:'in'|'out',bytes,json}",
    "Every raw JSON-RPC frame, both directions; last-resort ground truth.", true),
  p("editor.lsp.error.protocol", "lsp", "error",
    "{direction,method?,kind:'malformed'|'unhandled'|'transportClosed'|'sendWhileDisconnected',detail}",
    "A frame that didn't parse, a method we don't handle, a pending request orphaned by a dead transport, or a send attempted while disconnected."),
  p("editor.lsp.timing.request", "lsp", "timing", "{id,method,clockDelta,wallNanos}",
    "Per-request round trip; ordering by clockDelta, real time only in wallNanos."),
  p("editor.lsp.correlate.orphanResponse", "lsp", "branch", "{id,reason}",
    "A response whose request id we never sent (or already resolved); a wire/framing bug."),
  p("editor.lsp.hover.request", "lsp", "call", "{id,uri,position}",
    "Outbound textDocument/hover for the caret."),
  p("editor.lsp.hover.response", "lsp", "call", "{id,contents,range}",
    "Inbound hover payload; range must map to the token under the caret, not one column off."),
  p("editor.lsp.definition.request", "lsp", "call", "{id,uri,position}",
    "Outbound textDocument/definition."),
  p("editor.lsp.definition.response", "lsp", "call", "{id,locations:[{uri,range}]}",
    "Inbound definition target(s); the bridge to jump-to-declaration."),
  p("editor.lsp.documentSymbol.request", "lsp", "call", "{id,uri}",
    "Outbound textDocument/documentSymbol; the editor's own view of the file's declarations."),
  p("editor.lsp.documentSymbol.response", "lsp", "call",
    "{id,symbols:[{name,kind,range,selectionRange}]}",
    "Inbound symbol tree; each symbol's span must reconcile with a Tree 1 Node.span or the disagreement is logged."),
  p("editor.lsp.documentSymbol.reconcile", "lsp", "value",
    "{matched:[{symbolName,nodeId}],symbolsWithoutNode,nodesWithoutSymbol}",
    "documentSymbol spans reconciled against Tree 1 Node.spans — the editor's structure view agrees with the schema, or the disagreement is logged, never hidden (§9.11)."),
  p("editor.lsp.completion.request", "lsp", "call", "{id,uri,position,triggerKind}",
    "Outbound completion (deferred in skeleton but cataloged)."),
  p("editor.lsp.completion.response", "lsp", "call", "{id,itemCount,isIncomplete}",
    "Inbound completion list."),
  p("editor.lsp.semanticTokens.response", "lsp", "call", "{id,tokenCount,encoding}",
    "Inbound semantic tokens; ranges must decode without overrunning line lengths."),
  p("editor.lsp.foldingRange.response", "lsp", "call", "{id,ranges:[{startLine,endLine,kind}]}",
    "Inbound folding ranges."),
  p("editor.lsp.capability.unsupported", "lsp", "branch",
    "{method,reason:'server-does-not-advertise'}",
    "A feature request suppressed because the server didn't advertise it — server's lack, not a bug."),
  p("editor.lsp.out.didClose", "lsp", "call", "{uri}",
    "textDocument/didClose on dispose; missing it leaks server-side document state across runs."),
  p("editor.lsp.in.progress", "lsp", "call", "{token,kind:'begin'|'report'|'end',message}",
    "$/progress notifications; explains 'diagnostics arrived late' as server work, not a wire stall.", true),
  p("editor.lsp.in.logMessage", "lsp", "call", "{type,message}",
    "window/logMessage; the server's own log, surfaced rather than swallowed."),
  p("editor.lsp.in.showMessage", "lsp", "call", "{type,message}",
    "window/showMessage; a server-initiated user-facing message, never silently dropped."),
  p("editor.lsp.out.initialized", "lsp", "call", "{}",
    "The initialized notification completing the handshake; missing it leaves some servers silent."),
  p("editor.lsp.in.configuration", "lsp", "call", "{items}",
    "A workspace/configuration request from the server; what it asked for and what we answered."),
];
