/** Catalog sections S4 diag + S5 verdict (entries from §6; three payloadType
 *  field lists refreshed in the adversarial claim audit to match the emitted
 *  payloads — fill.decision, outline.decision, gutter.hover — and the
 *  green.blocked description rescoped to every guard-refusal cause, not just
 *  non-CT tiers). */

import { p, type ProbeSpec } from "./spec.js";

export const DIAG_PROBES: ProbeSpec[] = [
  // ── S4 diag ─────────────────────────────────────────────────────────────────
  p("editor.diag.input", "diag", "input", "{version,count}",
    "Diagnostics handed from S3 into the renderer."),
  p("editor.diag.uri.guard", "diag", "decision",
    "{diagUri,openUri,action:'apply'|'drop',reason}",
    "Whether a publishDiagnostics batch belongs to the OPEN document; another file's diagnostics are dropped LOUDLY, never painted onto this buffer (review finding: cross-URI batch applied)."),
  p("editor.diag.version.guard", "diag", "decision",
    "{diagVersion,modelVersion,action:'apply'|'drop',reason}",
    "Whether these diagnostics are current; a dropped stale batch is logged, never silent."),
  p("editor.diag.map.span", "diag", "value",
    "{diagId,lspRange,monacoRange,byteStart,byteEnd,positionEncoding}",
    "LSP-range → editor-range → byte-span mapping per diagnostic; where the squiggle's location is decided."),
  p("editor.diag.map.mismatch", "diag", "error",
    "{diagId,expectedByteStart,actualByteStart,delta,likelyCause:'utf16-utf8'|'eol'|'bom'}",
    "The span map produced an off-by-N; the cheap-connector-that-dies signal."),
  p("editor.diag.marker.set", "diag", "output",
    "{diagId,monacoRange,severity,message,source,code}",
    "The editor marker actually created (what the user sees)."),
  p("editor.diag.node.attach", "diag", "edge",
    "{diagId,nodeId,overlapKind:'contains'|'overlaps'|'exact'}",
    "The diagnostic bound to a Node.id by span overlap; how a compiler error becomes a node-level verdict input."),
  p("editor.diag.node.orphan", "diag", "branch", "{diagId,range,reason:'noNodeAtSpan'}",
    "A diagnostic whose span matches no node; either the span map or the schema is off."),
  p("editor.diag.severity.map", "diag", "decision",
    "{diagId,lspSeverity,markerSeverity,fillContribution:'red'|'amber'|'none'}",
    "LSP severity → marker severity → the verdict color it contributes."),
  p("editor.diag.related", "diag", "value",
    "{diagId,relatedInformation:[{uri,range,message}]}",
    "relatedInformation locations; each is span-mapped too and can drift the same way."),
  p("editor.diag.tag", "diag", "value", "{diagId,tags:['deprecated'|'unnecessary']}",
    "LSP diagnostic tags driving faded/struck rendering."),
  p("editor.diag.codeAction.available", "diag", "value", "{diagId,hasQuickFix}",
    "Whether the server offers a quick-fix (lightbulb); cataloged now, surfaced when features thicken."),
  p("editor.diag.clear", "diag", "state", "{version,clearedCount}",
    "Markers cleared before applying a new batch; a leaked marker means stale squiggles."),
];

export const VERDICT_PROBES: ProbeSpec[] = [
  // ── S5 verdict ──────────────────────────────────────────────────────────────
  p("editor.verdict.node.input", "verdict", "input",
    "{nodeId,schemaFill,schemaOutline,tier,liveDiagnostics:[diagId]}",
    "Everything known about a node's verdict before deciding what to paint."),
  p("editor.verdict.fill.decision", "verdict", "decision",
    "{nodeId,displayedStatus,source:'schema-fill'|'lsp-live'|'none',tier,greenAllowed,notChosen,reason}",
    "The per-node FILL decision AND the branch not taken."),
  p("editor.verdict.green.guard", "verdict", "decision",
    "{nodeId,wouldBeGreen,greenAllowed,tier,source,reason}",
    "The honesty gate: green permitted ONLY from a real compiler/kernel verdict at tier CT."),
  p("editor.verdict.green.blocked", "verdict", "branch",
    "{nodeId,downgradedTo:'unknown'|'blue',tier,reason:'green-may-never-be-faked'}",
    "A would-be green refused by the honesty guard — non-CT tier, empty fill.source, missing provenance, or provenance.resolved:false; fires loudly."),
  p("editor.verdict.unknown.render", "verdict", "value",
    "{nodeId,status:'unknown',renderedAs:'unknown'}",
    "Proof that unknown renders AS unknown, never up-shaded to green."),
  p("editor.verdict.conflict", "verdict", "decision",
    "{nodeId,schemaStatus,liveStatus,winner,reason}",
    "Schema FILL vs live diagnostics disagree; which wins and why (never past the green guard)."),
  p("editor.verdict.gutter.paint", "verdict", "output",
    "{nodeId,lineNumber,glyphClass,color,status}",
    "The FILL gutter decoration painted."),
  p("editor.verdict.outline.decision", "verdict", "decision",
    "{nodeId,worstOf,chosen,order:'red>amber>blue>definition>lemma>none/green',displayedStatus,statusMapping,unrecognizedVocab,schemaStatus,recomputedMatchesSchema}",
    "The OUTLINE trust-base status via worst-case-wins over outline.worstOf."),
  p("editor.verdict.outline.paint", "verdict", "output", "{nodeId,ringColor,status}",
    "The OUTLINE ring/badge painted."),
  p("editor.verdict.outline.null", "verdict", "branch",
    "{nodeId,reason:'outline-not-computed-yet'}",
    "Node.outline is null (gap analysis hasn't run); renders 'not yet computed', never green."),
  p("editor.verdict.origin.map", "verdict", "decision",
    "{nodeId,origin:'given'|'assumed'|'checked',treatment:'blue'|'amber'|'verdict-color',reason}",
    "How Node.origin maps to a visual treatment; keeps assumed debt visually distinct from a real verdict."),
  p("editor.verdict.legend", "verdict", "value", "{entries:[{status,meaning,source}]}",
    "The legend the user sees; the human-readable contract that green means a real compiler verdict."),
  p("editor.verdict.gutter.hover", "verdict", "value",
    "{nodeId,tooltip:{status,source,tier,serverName,provenance,decided,note}}",
    "The provenance tooltip on a gutter glyph; where the user reads WHY a node is its color."),
];
