/** Catalog sections S6 select + S7 map (entries from §6; two payloadType
 *  field lists refreshed in the adversarial claim audit to match the emitted
 *  payloads — emit.multi gained reason, map.build.input gained encoding). */

import { p, type ProbeSpec } from "./spec.js";

export const SELECT_PROBES: ProbeSpec[] = [
  // ── S6 select ───────────────────────────────────────────────────────────────
  p("editor.select.emit.cursor", "select", "input", "{position:{line,column},selection}",
    "The raw cursor/selection change that starts an emit."),
  p("editor.select.emit.resolve", "select", "value",
    "{position,nodeId,span,matchKind:'innermost'}",
    "The caret resolved to its containing node via S7."),
  p("editor.select.emit.miss", "select", "branch", "{position,reason:'noNodeAtCaret'}",
    "Caret in no node's span; nothing is emitted — why the graph didn't highlight."),
  p("editor.select.emit.bus", "select", "output",
    "{busEvent:{type:'node.select',nodeId,origin:'editor',clock}}",
    "The Node.id emitted on the bus; must be byte-identical to Tree 1's id, never re-derived."),
  p("editor.select.recv.bus", "select", "input", "{nodeId,origin}",
    "An id arriving from the bus (e.g. from Tree 5)."),
  p("editor.select.recv.lookup", "select", "value", "{nodeId,span,found}",
    "The received id resolved to a span via S7."),
  p("editor.select.recv.miss", "select", "branch", "{nodeId,reason:'idNotInThisFile'}",
    "A received id not in this file's index; ignored on purpose (another pane's), logged."),
  p("editor.select.recv.reveal", "select", "output",
    "{nodeId,monacoRange,revealed:'center',highlightApplied}",
    "revealRangeInCenter + highlight applied to the span."),
  p("editor.select.echo.guard", "select", "decision", "{nodeId,suppressedReEmit,reason}",
    "The feedback-loop guard: a received id must not re-emit."),
  p("editor.select.emit.multi", "select", "branch",
    "{selectionCount,nodeIds,policy:'primary-caret'|'all',reason}",
    "A multi-cursor selection spanning several nodes; which id(s) emit and by what policy."),
  p("editor.select.emit.debounce", "select", "decision",
    "{rawEvents,emitted,windowMs,reason}",
    "Selection-change debouncing; a rate cap logged rather than silently coalescing emits."),
  p("editor.select.timing", "select", "timing",
    "{emitToBusClockDelta,busToHighlightClockDelta,wallNanos}",
    "Brushing latency, both directions."),
];

export const MAP_PROBES: ProbeSpec[] = [
  // ── S7 map ──────────────────────────────────────────────────────────────────
  p("editor.map.build.input", "map", "input", "{fileUri,nodeCount,encoding}",
    "The schema nodes for this file handed to the indexer."),
  p("editor.map.build.index", "map", "output",
    "{nodeCount,intervalCount,overlaps,builtAtVersion}",
    "The SpanIndex built."),
  p("editor.map.byte.to.pos", "map", "value",
    "{byteOffset,line,column,positionEncoding}",
    "A byte offset converted to an editor line/column.", true),
  p("editor.map.pos.to.byte", "map", "value",
    "{line,column,byteOffset,positionEncoding}",
    "The inverse conversion.", true),
  p("editor.map.encoding.mismatch", "map", "error",
    "{byteOffset,expectedColumn:naive-bytes-as-columns,actualColumn:achieved,deltaBytes,char,reason:'multibyte-utf16',midCodepoint}",
    "Byte↔column conversion desynced on a multibyte character (mid-codepoint landing or round-trip disagreement); expectedColumn is the naive bytes-as-columns reading so the off-by-N is visible in the payload."),
  p("editor.map.overlap.ambiguous", "map", "decision",
    "{position,candidates,chosen,rule:'innermost',reason}",
    "A position inside nested spans; which node wins."),
  p("editor.map.multifile", "map", "branch",
    "{nodeId,span:{file},reason:'not-this-file'}",
    "A schema node whose span points at another file; excluded from this file's index."),
  p("editor.map.build.conflict", "map", "decision", "{span,nodeIds,chosen,reason}",
    "Two schema nodes claiming the exact same byte span; surfaced, never silently coalesced."),
  p("editor.map.stale", "map", "state",
    "{builtAtVersion,currentVersion,action:'rebuild'}",
    "The buffer changed so the index is invalid; rebuilt rather than trusting stale coordinates."),
  p("editor.map.span.clamped", "map", "branch",
    "{nodeId,byteStart,byteEnd,fileByteLength,reason}",
    "A schema node span reaches past the file's actual bytes; clamped to EOF and surfaced (schema/file desync is a signal, never silently absorbed)."),
  p("editor.map.nodes.refresh", "map", "input",
    "{nodeCount,mounted,reason:'schema-nodes-updated'}",
    "Fresh schema nodes replaced the cell's node set (the wall's update() path); index rebuild, verdict repaint and viewport re-emit all chain to this probe — a real refresh path, never a silent re-mount (ASSEMBLY Phase 1)."),
];
